CREATE DATABASE QLSACH 
GO 
USE QLSACH 
CREATE TABLE SACH( 
MASACH NVARCHAR(10) PRIMARY KEY, 
TENSACH NVARCHAR(50), 
TACGIA NVARCHAR(50), 
NAMXB NVARCHAR(4), 
SOLUONG INT, 
IMAGECOVER NVARCHAR(50) 
) 
