//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTQLHocVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCVIEN
    {
        public string MAHOCVIEN { get; set; }
        public string TENHOCVIEN { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string GIOITINH { get; set; }
        public string EMAIL { get; set; }
        public string DIENTHOAI { get; set; }
        public string PROFILE { get; set; }
    }
}
