CREATE DATABASE QLHocVien;
GO

USE QLHocVien;
GO

CREATE TABLE HOCVIEN
(
    MAHOCVIEN VARCHAR(20) NOT NULL PRIMARY KEY,
    TENHOCVIEN NVARCHAR(100) NOT NULL,
    NGAYSINH DATE NULL,
    GIOITINH NVARCHAR(10) NULL,
    EMAIL VARCHAR(100) NULL,
    DIENTHOAI VARCHAR(15) NULL,
    PROFILE NVARCHAR(255) NULL
);
GO